### PR TITLE
Fix right click on empty psace in log don't show context menu

### LINKED ISSUE #352: right click in empty space in log window doesn't open context menu (dclick needed)
Probably not related to #348, but is it intented that the right click menu takes a double click to open when i click below the log instead of a single click when i click one of the log rows?

_Originally posted by @Joyomojo in https://github.com/EventGhost/EventGhost/issues/348#issuecomment-450649972_

### PR DESCRIPTION
**Pull request by topic2k**
Fixes #352

### CODE REVIEW

**Comment by kdschlosser** [comment]
it looks good. my question is why did this all of a sudden break? or has this bug been since the wxPython update?

**Comment by topic2k** [comment]
I guess it had been there but no one noticed it.

**Comment by kdschlosser** [comment]
I just tried an older version of EG and the context menu works fine..

so now the question is what did we do that has cause this issue????...

I can't think of anything off hand that has caused this to simply just happen... OOoo 

maybe it is only happening in windows 10?

**Comment by topic2k** [comment]
which version did you test?

**Comment by kdschlosser** [comment]
a WIP that i have

**Comment by kdschlosser** [comment]
```python
string = 'WIP-2018.05.25-17.43.19'
base = 'WIP'
major = 0
minor = 0
patch = 0
alpha = 0
beta = 0
rc = 0
buildTime = 1527270199.37
```

**Comment by gemboot** [comment]
> 
> 
> I guess it had been there but no one noticed it.

yes it's there for at least one full year, I've noticed it back then but since it was bothering the usage of EG i've never took the time to report it. So I can confirm that it's not something new :)

**Pull request merged**
