### PR TITLE
Fix passing of additional parameters to eg.SpinNumCtrl

### PR DESCRIPTION
**Pull request by kdschlosser**
Fixes the passing of any additional keywords to eg.SpinNumCtrl.
Removes old bug patches from eg.SpinNumCtrl that are no longer an issue
Removes unused style keyword from eg.SpinIntCtrl
Minor code Cleanup

### CODE REVIEW

**Comment by topic2k** [comment]
Please do separate commits for each of the fixes you listed (they can be in one PR).
In the title of the PR remove `[EventGhost]`. Text in square brackets indicates a plugin.
Besides that the code changes looks good to me.

**Comment by kdschlosser** [comment]
I will do the separate commits. but there is no plugin associated with this. it's a core widget.

**Comment by kdschlosser** [comment]
dammit I am still trying to get the hang of this github thing. sorry about the revert on the revert. but everything should be in order for the 2 commits you wanted.

**Comment by topic2k** [comment]
yeah, i'm still fighting with commits and pull requests 😄 

Maybe ask @CarsonF if he could assist you. I think he has good knowledge about git.

**Comment by kdschlosser** [comment]
damned thing is driving me crazy. because there is no way to undo without making and undo for an undo. and just deleting the PR is not the right thing to do either... there is no bloody way to fix a screw up without making a mess of it. quite frustrating.

**Comment by per1234** [comment]
My favorite approach for changing commit history is interactive rebase. In this case you would do:
```
git rebase -i 6c26
```
on your branch. This will start an interactive rebase of your commits(`6c26` is the first 4 characters of the last commit before your commits). This will open a text file with a list of commits and instructions of the different interactive rebase options. You can remove/edit/rearrange/etc. the commits. `fixup` is a useful option for merging two commits together.

Once you have finished configuring the interactive rebase close and save the text file and the rebase will proceed. If you're lucky there will be no merge conflicts and the rebase will complete successfully.

Next, check over the commit history to be sure that everything is as expected.

Now the problem is that your local branch is different from the remote branch. If you do a sync as usual it will pull in the commits you just got rid of from the remote branch, which is not what you want. So you need to do a force push instead:
```
git push -f
```
This will force git to push your changes to the remote branch, which will automatically update this pull request.

In gener changing commit history is a very bad idea but in the case of a development branch like your "bugfix-spintintctrl" it's perfectly fine and much preferable to adding unnecessary commits to the repository. You might want to note that you've done a force push in the comments here so everyone knows the commit history has been changed. You should never change commit history in a branch where other people are counting on it not changing. In that case it's better to just add more commits.

I'm not sure exactly what changes you want to make here so I can't provide more detailed instructions but I'm happy to provide more advice if needed. If so maybe we should move the discussion to email to avoid blowing up the other watchers' inboxes.

**Comment by kdschlosser** [comment]
OK there 2 widgets impacted by changes. I had originally done a commit containing the changes to both at once. he wants a commit for each widget

**Comment by topic2k** [comment]
I've done the changes manually.

**Pull request closed without merging**
