### PR TITLE
[Eventghost] - Requirement - Updates copyright notice

### PR DESCRIPTION
**Pull request by kdschlosser**
The PR title says it all.

### CODE REVIEW

**Comment by kdschlosser** [comment]
yeah never thought of that. I will go ahead and do this

**Comment by topic2k** [comment]
Hey, sorry to say that we now have conflicting files here. Didn't noticed that i should have merged this one before removing the COMserver. Please remove the file from this PR so i can merge it.

**Comment by kdschlosser** [comment]
The com server one was more then removing a single file. Probably best to close the PR and make a new one.

in all honesty ya know what I think should be done so we do not have to deal with this again.. we should build into the builder is having it add the header to all of the files including the proper year. Both yours and my name should also be attached to the headers. what do you think? 

This way it will roll the year when the project gets built. if needs be without having us having to remember to do it. as you can see we are a little late with this one.. LOL

**Comment by topic2k** [comment]
and that is already (partly) implemented: https://github.com/EventGhost/EventGhost/blob/master/_build/builder/CheckSourceCode.py

**Comment by kdschlosser** [comment]
That I know good sir.. 
Ya think it it is something we should do??? this way we will not have to remember to do it 
again in a few months??

**Comment by topic2k** [comment]
well, yes and no :smiley: would be nice to have to change it just in one place, but OTH how often do we really need to change it? one-twotimes a year?

**Comment by kdschlosser** [comment]
that is all we have to change it.. But the thing is see how good we are at remembering?? it's october of 2018 little late in the game yes?? it is something that is very easily forgotten and having the builder make sure it is current I think may be a wise decision.. You are the head of the coding arena so it is ultimately which ever you would like to do.. I am only going to provide information that will lead to the best possible outcome..

All I am saying is to date we have a pretty crappy track record of making sure it gets updated on time. LOL

**Comment by dequi** [comment]
This seems an easy one. Do manual now and and I'll help you remember in three months :smile:

**Comment by kdschlosser** [comment]
@dequi funny. I remembered to do it last time. and see where that got us.

I think it is best if I delete this PR and make a new one. the resolve conflicts button is grayed out and says that the conflicts are too complex. LOL

**Comment by topic2k** [comment]
Wouldn't it be enough to remove COMserver.py from your branch https://github.com/kdschlosser/EventGhost/tree/update-copyright ?

**Comment by kdschlosser** [comment]
that change is not simply deleting the one file.
and because it is not telling you anything other then that single file i am willing to bet there are all kinds of conflicts. it is simply not displaying them

**Comment by dequi** [comment]
Still learning git/github but it seems you deleted **_eg/WinApi/COMServer.py_** added **_eg/WinApi/GenPaths.py_** and changed a few lines in **_eg/Init.py_** in commit 680d62610be353e1281d8f11f145fa823a5fcfff , so... not so many conflicts, or am I missing something?

**Comment by kdschlosser** [comment]
OK so how Github figures out what is a conflict.
When this PR gets compared against the branch the PR has been submitted to it knows what code has changed. if it sees that the branch differs in any way except for the changes in the PR it's self. it is going to produce a conflict. so say we have PR1. then PR2 gets issued after PR1. but PR2 gets merged before PR1 this will cause PR1 to have a conflict.

so the conflicts are cumulative of every PR that has been merged since this PR's inception. So it is simply not a single file issue. If it was just those couple of items it would be able to be handled by the Resolve Conflicts button. There have been many changes since Jan 3rd. we would have to go and look at what PR's have been merged since then.

#283, #288, #294,  #296, #298, #299, #300, #301, #302, #303, #307, #309, #316, #317 

all of the above hav been merged since Jan 3rd.

**Comment by kdschlosser** [comment]
OK this should be good to go now.

**Comment by topic2k** [comment]
please rebase on master or merge master so that i can merge this PR.

**Comment by kdschlosser** [comment]
Would love to if you can tell me how to do it from my cell phone.

**Comment by topic2k** [comment]
oh, from cell phone... hmm.. do it when you're back at home and have some time. No need to hurry.

**Comment by kdschlosser** [comment]
screw this one we are now into a new year i am going to close it

**Pull request closed without merging**
