### PR TITLE
Upgrade to wxPython 3.0

### LINKED ISSUE #9: Upgrade to the latest wxPython
If a version of wxPython > v2.8 is the default version, the main frame of EG is shown, but then the app hangs.

### PR DESCRIPTION
**Pull request by topic2k**
Resolves #9.

**_For (plugin) developers:_**
Take a look at the [changes since wxWidgets 2.8](http://docs.wxwidgets.org/stable/overview_changes_since28.html), [wxPython 2.9 Migration Guide](http://wxpython.org/migrationguide.php) and [the deprecated functions list](http://docs.wxwidgets.org/stable/deprecated.html).
What is not described there and we found out:
- If you use a `GridBagSizer` with growable rows/columns, be sure to set the growable row/column after you added the corresponding row/column. Example:
```
sizer = wx.GridBagSizer()
sizer.AddMany([
    (self.slider, (0, 0), (1, 3), wx.EXPAND),
    (st1, (1, 0), (1, 1), wx.ALIGN_LEFT),
    (self.valueLabelCtrl, (1, 1), (1, 1), wx.ALIGN_CENTER_HORIZONTAL),
    (st2, (1, 2), (1, 1), wx.ALIGN_RIGHT),
    ])
sizer.AddGrowableCol(1, 1)
```

### CODE REVIEW

**Comment by blackwind** [comment]
Looks like there might be a few more commits you left out, unless you decided those weren't necessary after all. "Files changed" at the top of this PR says 16, while the old one says 33.

**Comment by topic2k** [comment]
Yeah, right. Changes to the plugins are missing. I currently look at the diff of the previous PR and redo the changes.

**Comment by topic2k** [comment]
Added the changes to the plugins for AddGrowableRow/Col.

**Comment by blackwind** [comment]
`eg/Classes/StaticTextBox.py` and `eg/Classes/TreeItem.py` are still missing, I see a different number of changes in `plugins/Webserver/__init__.py`, and I'm wondering if `images/finderte.png` was supposed to be deleted.

**Comment by topic2k** [comment]
Good Morning. `eg/Classes/StaticTextBox.py` was just a removal of a redundant style flag.
In `plugins/Webserver/__init__.py` i left out non-wx changes. In my python installation i have version 0.2.1 of websocket and there `WebSocketApp` is renamed to `WebSocket`. But as i don't use it, i can't really test it.

**Comment by blackwind** [comment]
Gotcha. I guess we're good, then. Testing is still going well on this end, and I still plan to merge by the end of the week.

**Pull request merged**
