### PR TITLE
Webserver plugin updates(with commit for each version)

### PR DESCRIPTION
**Pull request by per1234**
This is a reworking of https://github.com/EventGhost/EventGhost/pull/126 which results in identical changes but with a separate commit for each plugin version.

Webserver 3.12.1 is problematic because it was not based on the up to date plugin code and thus introduces regressions. If you would prefer that commit was squashed into 3.13 I am happy to do so but I do think it's best for every released version of the plugin to be available in the commit history.

Ideally each change would have been submitted as a separate pull request as they were made and I'd be happy to break this into separate PRs on request. My goal here is just to create a more meaningful commit history than #126. For this reason please don't squash these commits into a single commit during the merge.

cc: @ThomasBott @david-mark

EDIT: supersedes #126, #116

### CODE REVIEW

**Comment by kdschlosser** [comment]
I think that because of the complexities of the webserver plugin in all honesty it should be in it's own repository. actually each and every single plugin should be that way it's easier to identify what has been done to what plugin. but also to keep changes to the "core" separated from the plugins. if the ultimate goal is to not distribute any plugins with a release of EG. then this kind of thing should be instituted now instead of later. but will lead to a much better organization. Should there also be a standard set in place that if you make a plugin it has to be added to a github page in order to be added to the plugin repository? that way a fork can be done for the plugin and suggestions to the plugin developer can be easily made and suggestions on coding style. and things of that nature, But also a template can be put up so that someone new to making a plugin has something they themselves can fork and then use to start their plugin development.

**Comment by topic2k** [comment]
> I think that because of the complexities of the webserver plugin in all honesty it should be in it's own repository.
That's the goal of the plugin repository/manager. But until we have that, i think we should commit plugin changes to this github repo.

**Comment by ThomasBott** [comment]
Thank you @per1234 !

**Comment by topic2k** [comment]
Thanks for doing this, now i can delete my unfinished branch with this commits 😄

**Pull request merged**
