### PR TITLE
Fix Broadcaster Unicode encoding and decoding

### PR DESCRIPTION
**Pull request by david-mark**
...After a bit of fumbling around with comment and white space issues between the repo and my installed version of this plug-in. :(

Brings into line with Network Sender and Network Receiver plug-ins and fixes decoding exceptions on TriggerEvent call

### CODE REVIEW

**Comment by david-mark** [comment]
Fully tested with all manner of non-ascii Unicode characters for event name, payload and delimiter.

**Comment by per1234** [comment]
Please squash the commits before or during the merge to keep the commit history clean.

**Comment by david-mark** [comment]
I sure would if I had a clue how to do that. Never heard of a "squash" Git command. :)

I did these from the Website, so wonder if there is a way to do it from there. Will look into it for future reference.

Was a major pain in the neck dealing with the differences between my version and what is in this repository. I'm sure lots of people have the same problem as many plug-ins are maintained on some lousy bulletin board forum, apparently with long passages between merges. :(

**Comment by david-mark** [comment]
Oops, there I go again. Not used to doing this on the Website. Seems like I have to create a branch of my own code and then merge it, which seems like a hard way to go. Sure I'm just missing something.

**Comment by topic2k** [comment]
I can squash the commits before merging the PR.

**Comment by david-mark** [comment]
Thanks very much topic2k. That will definitely help the process as I'm still not sure how to do this through the Website and don't care to mess with this project through Git proper at the moment (many of my files vary wildly from what's here). I'm just copying and pasting in patches at the moment. I do hope that whatever rift exists between the BB forum and this repository is bridged in the near future as development is help back by this fragmentation.

**Pull request merged**
