### PR TITLE
Bring the git repository on line with the svn version.

### PR DESCRIPTION
**Pull request by topic2k**
Updates in svn since last git commit:

- r1724  Plugin Webserver - bugfix (Send all values)
- r1723  Plugin Webserver - bugfix - Action "Send Value" or "Broadcast Value", when value is persistent
- r1722  Plugin MediaMonkey - update
- r1721  pycurl update
- r1720  
- r1719  Added psutil library (Sem;colon's suggestion)
- r1718  Plugin EventGhost update (Sem;colon, Pako)
- r1717  Plugin SchedulGhost - update (Sem;colon)
- r1716  Plugin Webserver update (Sem;colon, Pako)
- r1715  Plugin Keyboard - blackwind's patch (WIn 10 issue)
- r1714  Plugin System - bugfix
- r1713  Plugin System - added action "Show QR code"
- r1712  PluginInstanceInfo.py - suppression of "DeprecationWarning: BaseException.message has been deprecated as of Python 2.6"
-  1711  Plugin Speech - bugfix (translate problem)
- r1710  Plugins Directory Watcher and Network Event Receiver - added "Support Plugin" link
- r1709  Plugin Schedulghost - Sem;colon's update - checkboxes affecting the behavior of the schedule during the holidays now not distinguish between work and weekend days
- r1708  Plugin Network Event Receiver - pearbear's update - this fixes the security vulnerability of the same cookie being sent for every received event
- r1707  Plugin System - actions Execute and Command - added option "Run as Administrator"
- r1706  http://www.eventghost.net/forum/viewtopic.php?f=4&t=7315
- r1705  Plugin Webserver - Filandre's change: Websockets support for old browsers (Hixie-76 protocol, especially for early iPad) and also support for IE10/11
- r1704  Sem;colon's modification to eg/WinApi/SendKeys.py: - Improved Error handling (previously it was possible that it crashes if a Key could not be parsed correctly) - Added the parameter "mode" which specifies if the button(s) should be pressed...
- r1703  Plugin Speech - added option for selection of date and time format
- r1702  Plugin Speech - added option for selection of output device
- r1701  Plugin Speech - added event after speaking finished - {DATE} context is working properly
- r1700  Plugin Webserver - improved reliability WebSocket connection (Ping/Pong protocol)
- r1699  Plugin SchedulGhost - Immediate start schedule now has no effect on the scheduled run
- r1698  XBMC2 plugin - update
- r1697  Plugin Mouse - Sem;colon's improvements http://www.eventghost.net/forum/viewtopic.php?f=9&t=5481#p34507
- r1696  The "Apply" button does not enable, when a slider in the ConfigPanel  is changed http://www.eventghost.net/forum/viewtopic.php?f=10&t=6769&p=34349#p34338
- r1695  Plugin OSM - The Back part of event is divided only by the first found dot
- r1694  Plugin Window - cleanup of code
- r1693  Plugin Window - bugfix (EventGhost crashes when using the action "Minimize to Tray")
- r1692  Plugin Snarl - signature no longer contains version string
- r1691  Plugin System - Action "Change Registry Value" - sdded ability to insert a new value as a variable
- r1690  Bugfix - the characters don't get properly encoded in the XML when copying from configuration tree
- r1689  Plugin MediaPlayerClassic - bugfix - Find_MPC() function now works also in 64-bit system
- r1688  Added pycurl library
- r1687  Update of paramiko library (version 1.15.1)
- r1686  Plugin System - action Windows Command - update
- r1685  Plugin EventGhost - action Jump with "Else" option - bugfix
- r1684  Plugin Webserver - added WebSocket client actions
- r1683  Plugin System - added action "Windows Command"
- r1682  SunTracker and Scheduler plugins - update
- r1681  Plugin MediaPlayerClassic - the function GetMpcHcPath() improved
- r1680  Plugin EventGhost - added action 'Jump with "Else" option'
- r1679  Plugin OSM - bugfix (Test button on dialog "Show menu")
- r1678  eg.Utils - added GetUpTime and GetBootTimestamp functions Plugin System - added GetUpTime and GetBootTimestamp actions
- r1677  Plugin MediaPlayerClassic - bugfix (action GetNowPlaying)
- r1676  Added pyaudio and websocket libraries
- r1675  SchedulGhost plugin - http://www.eventghost.net/forum/viewtopic.php?f=9&t=2740&start=90#p33284
- r1674  Possibility to listen events within a plugin http://www.eventghost.net/forum/viewtopic.php?f=10&t=6218&start=15#p33045
- r1673  Plugin System - http://www.eventghost.net/forum/viewtopic.php?f=10&t=6195 - http://www.eventghost.net/forum/viewtopic.php?f=4&t=6187&p=33279#p33121
- r1672  Plugin EventGhost - action "Open configuration dialogue" added
- r1671  Media Player Classic plugin - bugfix (Show menu when fullscreen)
- r1670  A Snarl stock icons can be specified (such as "!system-warning")
- r1669  Plugin SunTracker - version 1.5.4
- r1668  Plugin Scheduler - version 1.2.1
- r1667  Plugin XBMC - version 0.6.14 - http://www.eventghost.net/forum/viewtopic.php?f=9&t=1562&start=930#p30002
- r1666  Some plugins- changes caused by a new eg.Scheduler
- r1665  Plugin SchedulGhost - - changes caused by a new eg.Scheduler
- r1664  Added libraries tornado, paramiko and requests
- r1663  Plugin SunTracker - version 1.5.2
- r1662  Plugin MceRemote_Vista - http://www.eventghost.net/forum/viewtopic.php?f=9&t=6044#p30007
- r1661  Plugin Task - http://www.eventghost.net/forum/viewtopic.php?f=9&t=6086#p30856
- r1660  Plugin System/Sound - http://www.eventghost.net/forum/viewtopic.php?f=2&t=5754#p28366
- r1659  Plugin System - http://www.eventghost.net/forum/viewtopic.php?f=4&t=5471
- r1658  Scheduler.py - http://www.eventghost.net/forum/viewtopic.php?f=10&t=6145
- r1657  Plugin PHX01RN - version 3.0.1 - http://www.eventghost.net/forum/viewtopic.php?f=9&t=5927#p28901
- r1656  Plugin Webserver - version 2.1 - http://www.eventghost.net/forum/viewtopic.php?f=9&t=1663&start=60#p29831
- r1655  Plugin Winamp - version 1.4.2 - http://www.eventghost.net/forum/viewtopic.php?f=9&t=201&start=15#p28466
- r1654  Plugin MCE_Vista - version 1.1.1 - http://www.eventghost.net/forum/viewtopic.php?f=9&t=6044#p30007
- r1653  Plugin SchedulGhost deleted from "not-included-plugins" folder
- r1652  Plugin SchedulGhost - added action "Force to run schedule immediately"
- r1651  SchedulGhost plugin - added option to abort egg-timer by name
- r1650  Plugin Snarl - customized events on notification disappearance can carry a payload now and supports also variables
- r1649  Snarl plugin - notification user menu now supports also variables
- r1648  Snarl Plugin - bugfix              - notification menu now supports also event payload
- r1647  Plugin SchedulGhost - http://www.eventghost.net/forum/viewtopic.php?f=9&t=2740&start=75#p30126

### CODE REVIEW

**Comment by blackwind** [comment]
We want to preserve the complete SVN history in this repo. I'd be happy to approve a pull request containing a single commit (attributed to user "pako2") for each revision, but as is, this one is a no-go.

Note that we can't complete the transition to GitHub until someone works out the build scripts. As you've noted on [the forum](http://www.eventghost.net/forum/viewtopic.php?f=10&t=8050), building from source is currently impossible for anyone but Pako. Until that changes, he plans to continue using SVN, so if you plan to undertake the updating of this repo, know that it'll be an ongoing process.

As for the "not-included-plugins", I'll be suggesting to Pako when the time comes to keep these in a separate repo under his user account. If they're not included in the official distribution, they shouldn't be included in the official repo.

**Comment by topic2k** [comment]
Ok, understand. I will investigate how to keep the history and attribute the commits to pako2.
Meanwhile i was able to build the installer and have a first working with the git repo (but needs some more tweaking).

**Comment by blackwind** [comment]
Excellent, I can't wait to see your work!

**Comment by blackwind** [comment]
Another option for you: I've created [an alternate, fully updated repo](https://github.com/EventGhost/EventGhost-import) using [GitHub Importer](https://import.github.com/new). If you can remove not-included-plugins and figure out how to get the Bitmonster and Pako branches successfully merged into master, send a pull request, and we'll switch to that repo.

**Pull request closed without merging**
