### PR TITLE
[EventGhost] TriggerEvent: option to remove the 'Main' prefix

### LINKED ISSUE #350: Changed "Trigger Event" behavior when event string contans a dot
A significant breaking change was introduced by https://github.com/EventGhost/EventGhost/pull/279/commits/294f16bf838cb58962cec90d7628545293343c6a. 

Prior to that commit, this action:
```python
eg.plugins.EventGhost.TriggerEvent(u'foo.bar', 0.0, None, False, False)
```
would trigger the event `Main.foo.bar`. After the commit, the triggered event is `foo.bar`. The `Main.` is now only added when the event string does not contain a dot.

I previously reported this at https://github.com/EventGhost/EventGhost/pull/279#issuecomment-356185110. At that time, @kdschlosser's plan to fix this was:
>I can add a checkbox to enable or disable the Main prefix and have it set to off as a default.

But that still hasn't happened. In order to avoid having this issue get forgotten in a comment thread of a merged PR, I'm creating a dedicated issue.

### PR DESCRIPTION
**Pull request by kdschlosser**
I added an option to the Trigger Event action to remove the main prefix.

Fixes #350

### CODE REVIEW

**Comment by per1234** [comment]
Thanks @kdschlosser!

I'm using the test build and I noticed a bug:

1. Create a Trigger Event action.
2. Check the 'Remove "Main" Prefix' checkbox.
3. Click "OK".
4. Double click the action. The 'Remove "Main" Prefix' checkbox is now unchecked.

I also find it a bit unintuitive that the 'Remove "Main" Prefix' checkbox doesn't work as advertised when the event string does not contain a dot. I understand why the "Main" prefix is still added in that case but I think it could be confusing for some users. I'm not sure what the best way would be to resolve that without unnecessary verbosity in the dialog. Maybe change the text to: 'Remove "Main" prefix when custom prefix is specified'? That's still pretty long. Is it possible to automatically enable/disable the option according to the contents of the "Event string to fire" input field?

**Comment by kdschlosser** [comment]
HA! you are correct sir. I forgot to set the default value for the check box.

**Comment by kdschlosser** [comment]
OK it should be good to go. provided i didn't fat finger something

**Comment by kdschlosser** [comment]
no worries m8. sorry I forgot about ya. Thanks for bringing  this up again i do appreciate it.

**Pull request merged**
