### PR TITLE
[System] - Code Cleanup - System, Cleans up code

### PR DESCRIPTION
**Pull request by kdschlosser**
Code cleanup/formatting
Moves all internationalism to a single Text class in __init__

### CODE REVIEW

**Comment by topic2k** [comment]
That's a big PR with lot of changes. I would prefer to have it split, either as more commits or more PR's:
- white space changes
- import changes
- text class changes
- code changes (variable names, line splits, etc.)
- (other?)

**Comment by kdschlosser** [comment]
can do. would you like them as PR's or commits?

**Comment by kdschlosser** [comment]
Oh one other thing. I would actually prefer is each file had it's own text class I would have to go and do some legwork to see if that would be possible to do with breaking the existing language files. but if it does break the the API then how the text classes are handled could get changed in a manner that could handle it. that would be something we could work on in the future and for now this would be fine. but I am making a comment about it for reference.

**Comment by topic2k** [comment]
One PR with serveral commits is ok.

**Comment by kdschlosser** [comment]
Going to redo do to single commit for all changes.

**Pull request closed without merging**
