### PR TITLE
[EventGhost] - Update - VistaVolEvents and VS Project

### PR DESCRIPTION
**Pull request by kdschlosser**
Updates VistaVolEvents Visual Studio project to use VS 2017
Changes external library to use PYTHON_LIB environment variable
Changes includes path to use PYTHON_INCLUDE environment variable
Fixes outfile not matching Linker
Changes src to remove any compile warnings.
Replaces VistaVolEvents.pyd to one compiled with VS2017

It seems to work even tho the file size went from 101k to 14k

### CODE REVIEW

**Comment by kdschlosser** [comment]
I am not sure why appveyor is failing. but On my appveyor account it builds fine,

https://ci.appveyor.com/project/kdschlosser/eventghost-9ivlx/build/439-updates-vistavolevents

**Comment by kdschlosser** [comment]
well that's strange. I just checked and it did build successfully but here it states it didn't

**Comment by kdschlosser** [comment]
I sent an e-mail into appveyor asking about this. We have also had it report a success when it actually failed the build. Lets see what they have to say about it. could be something in the setup. but i do not think so.

**Comment by kdschlosser** [comment]
https://ci.appveyor.com/project/topic2k/eventghost/history

it doesn't even show that appveyor tried to build the thing.

**Comment by kdschlosser** [comment]
would you believe that appveyor still has not responded to my inquiry about this.

**Comment by topic2k** [comment]
Yes, i can believe it. I'm waiting already a month for a fix. https://github.com/appveyor/ci/issues/1646

**Pull request closed without merging**
