### PR TITLE
[Speech] nearly complete rewrite of the plugin

### PR DESCRIPTION
**Pull request by topic2k**
- fix the usage of the text class (@kdschlosser)
- reworked the internal code of the plugin (@kdschlosser)
- code cleanup (@topic2k)

closes #172, #156, #148

### CODE REVIEW

**Comment by kdschlosser** [comment]
I am going to take a look at it as well so maybe i can get a better understanding of how it's broken apart... it is easier to do it afterwards i am thinking. because i tend to make to many changes during the process. and I would end up with a commit mess. Because if i did just the Text stuff with the way the plugin was done it would be completely different then how it is now. so i would end up redoing it and having another commit for that one.. I can't grasp why someone would want to go through that kind of work. to do something knowing it's going to be completely different later on for the sake of having a commit for the steps even tho the steps are going to require another commit to change them to the final way.

**Comment by kdschlosser** [comment]
see OK i just looked.. it's missing things.. there were original calls from the thread class to the text class these i never changed i removed them. but in this PR they are there and were modified. so why would I go and change the code knowing i was going to be removing it? why would that need to be done?. I just want some clarification on this.. because in all honesty it makes it more confusing to me seeing a commit and then the commit right after it.. and now that change is gone.

**Comment by per1234** [comment]
It's very easy to get distracted while coding and go off in multiple directions simultaneously. Start working on one task. notice an unrelated thing that needs fixing, and it's down the rabbit hole from there. Obviously you're very good at working that way but when you're involved in a collaborative project it's important to work in an atomic manner for the sake of the other people involved. It's much easier for you to decipher what you've done than others looking at your work. I've found even the familiarity with my own work fades over time. I look back at old code I wrote and am extremely grateful for any effort at documentation I might have made.

My advice is to stick to the one task you started on until it's finished, test, then commit. If you see other things that need to be changed along the way just add them to a to-do list. It takes some discipline but I've found enforcing this style of programming on myself has greatly improved the quality of my work and reduced the difficulty of debugging. I do this even for my own private projects now even though nobody but me will ever see those commits.

Unless multiple commits are integrally related, submit each one as a separate pull request. That way if any changes need to be made you can just add more fix up commits to that PR's branch and topik2k can squash them into a single commit when the PR is merged. That's not possible if you combine unrelated tasks into a single PR, then you end up having to mess with rebasing, possible merge conflicts, and force pushes when one of the multiple commits in the PR needs an edit..

**Comment by kdschlosser** [comment]
as i said my main focus was actually the win32com issue. but in order to get it changed about where it wasn't creating an instance of the sapi inside of a thread i had to change the text around. it was more like a side effect. LOL and unfortunately i found out that i couldn't just create one instance of the sapi and just keep on altering the same one.. even tho i passed the ID to the thread and then brought it up that way it still didn't work properly. so i ended up having to create a new instance each and every single time. but the code came out cleaner this way. Technically speaking the old plugin now works the way it was. just doctor up the text issue and it would have been good to go.. I didn't know it would lead to me patching win32com

**Comment by kdschlosser** [comment]
your not understanding... they were related. maybe not the pep 8 crap. but if i am just about recoding the whole thing. i am not going to go through the original fix all the coding style problems. then go and delete 1/2 of it in the process of rewriting it. I don't get where that makes any sense. 

put it to you this way... if you have a file with 1000 lines of code.. and said file has 5000 coding violations. and you are going to be re writing 500 of the 1000 lines.. 

so your saying to go through and fix the 5000 style issues... then delete 500 lines containing 2500 of the style issues you just spent the time to fix to write the new 500 lines?

**Pull request merged**
