### PR TITLE
Generate changelog from pull requests

### LINKED ISSUE #15: Generate changelog from pull requests instead of commits
@topic2k's build script update (#8) contains the ability to generate a changelog from Git commits. I suggested we only include the title/subject of each commit rather than the full body, but I fear this will still produce far too much noise for the end-user.

Consider the following recent commit messages:

* "Added README with project description and slack link"
* "Restored manifest file."
* "Merge pull request #8 from topic2k/develop"
* "Add .gitignore"

Do we really want all that in the changelog? Does the user care about any of these things?

Here's what I'm thinking we should include, ordered by order in the changelog:

* Merged pull requests with the `notice` tag ("Important changes for plugin developers:")
* Merged pull requests with the `enhancement` tag ("Features added:")
    * Except where also tagged with `internal`
* Merged pull requests with the `bug` tag ("Bugs fixed:")
    * Except where also tagged with `internal`

There's a Ruby project called [GitHub Changelog Generator](https://github.com/skywinder/github-changelog-generator) capable of producing this result. I don't think we should use that project directly to generate our changelog, as the last thing we need is a dependency on another language, but I think we should aim to reproduce [its excellent Markdown output format](https://github.com/skywinder/Github-Changelog-Generator/blob/master/CHANGELOG.md).

Added bonuses:

* If this completely eliminates the need for `pygit2` (and, by extension, libgit2), the process of setting up a build environment will be greatly simplified.
* We can publish the Markdown output to our GitHub releases (#14).

We need to resolve this before closing #2.

### PR DESCRIPTION
**Pull request by topic2k**
Resolves #15, #2.

### CODE REVIEW

**Comment by blackwind** [comment]
Won't have time to do a full review until tomorrow, but a cursory pass through this indicates that you missed this comment:

> Oh, and make sure you're iterating through commits and looking for "Merge pull request #" to get the list of pull requests in the first place. Again, just searching for merged pull requests via the issues API might not tell us the full story. See the second comment in #15 for an explanation as to why.

For that reason, all the `old_release_date` stuff is problematic and should be removed. Instead, build a list of pull requests included in this release from commits, switch to `state="closed"` in the query, then use `if pr["number"] in included_prs`.

I'm also seeing a lot of code duplication between lines 108-143. This could be simplified with:

```
title_notice = "Important changes for plugin developers:"
title_enhancement = "Features added:"
title_bug = "Bugs fixed:"
title_other = "Other changes:"
prs[title_notice] = []
prs[title_enhancement] = []
prs[title_bug] = []
prs[title_other] = []

[...]

elif "notice" in labels:
    prs[title_notice].append(pr)
elif "enhancement" in labels:
    prs[title_enhancement].append(pr)
elif "bug" in labels:
    prs[title_bug].append(pr)
else:
    prs[title_other].append(pr)

[...]

for kind, items in prs.iteritems():
    if items:
        print "# %s" % kind
        new_logs.append("### %s\n" % kind)
        for pr in items:
            txt = "  - #{0} {1}".format(pr["number"], pr["title"])
            print txt
            new_logs.append(txt + "\n")
        new_logs.append("\n")
        print ""
```

**Comment by topic2k** [comment]
I tried to understand the problem with the release stuff, but i don't get it. Maybe a real repository for testing would help, but on the other hand maybe you could finish the pull request as it seems you know how to workaround the release problem.

**Comment by blackwind** [comment]
Understanding the problem isn't particularly important here -- as long as you build the list of PRs from commits, the code will work as intended. Previously, you were doing:

```
if msg.startswith("Merge pull request #"):
    continue
```

Instead of `continue`ing, extract the PR number from `msg` and add it to `included_prs`. Then, download the complete list of PRs (without `since=old_release_date`) and only operate on the ones you added to `included_prs` (`if pr["number"] in included_prs`).

**Comment by topic2k** [comment]
ok, another try (even if i don't understand the difference :) ).

**Comment by blackwind** [comment]
`_build/builder/BuildChangelog.py`

* [lines 19, 20] Swap these lines. Try to remember to use alphabetical order for your imports from here on out.

* [lines 47-52] This code has the same problem as the original method. Instead, use:

```
rc, data = gh.repos[user][repo].git.refs.tags.get()
if rc != 200:
    print "INFO: couldn't get tags."
    return
to_commits = [i["object"]["sha"] for i in data]
```

* [lines 68, 76] Change to `if item['sha'] in to_commits:`.

* [lines 98, 119, 131] Remove.

* [line 111] Doing this one-by-one slows things down too much. Try the [Search API](https://developer.github.com/v3/search/) using [these parameters](https://api.github.com/search/issues?q=type:pr+is:merged+-label:internal+user:EventGhost+repo:EventGhost&sort=created&order=asc), which will return the entire batch in one query.

* [line 141] Remove so we don't get two blank lines at EOF. Extra newlines are added at line 170 if needed.

* [lines 174-196] No longer used. Remove.

`_build/builder/Utils.py`

* To prevent potential oversights, modify `GetGitHubConfig()` to find the name of the current branch being worked on locally. If that branch exists remotely, default `branch` to it instead of `repo["default_branch"]`.

Finally, let's make the file output look as close to the [GitHub Changelog Generator output](https://github.com/skywinder/Github-Changelog-Generator/blob/master/CHANGELOG.md) as possible. Don't forget to add version number, date, links to the PRs, and links to the authors.

**Comment by blackwind** [comment]
First, a few tiny nitpicks:

* [lines 22-23] Move to top of import list. Wildcard (*) imports first, then standard imports, then `from` imports.

* [lines 30, 43] Remove extra newline. Two lines of separating whitespace after(!) classes, one line everywhere else.

* [lines 31-41] Move to EOF. Classes should come before functions whenever possible.

See #52 for a complete list of things to keep an eye out for now that the codebase has been overhauled.

---

`_build/builder/BuildChangelog.py`

* [lines 97-111] No longer used. Remove and move lines 124-142 up here so the comment at line 113 makes sense.

* [line 134] I notice all the other `agithub` requests contain `per_page=100` and `page=page`. Will `NextPage()` work without them? If not, fix needed here.

* [line 168] Change to `"https://github.com/{0}/{1}/releases/tag/v{2}".format(`. Missed the "v".

`_build/builder/Utils.py`

* [line 129] Add `local_branch = ""` below here just in case `local_branch` doesn't get defined.

* [line 130] Use `--porcelain` whenever possible when running Git commands. According to the documentation:

> The porcelain format is similar to the short format, but is guaranteed not to change in a backwards-incompatible way between Git versions or based on user configuration. This makes it ideal for parsing by scripts.

* [line 131] Use `subprocess.check_output(cmd)` here for much cleaner code. Be sure to handle the error in case Git isn't installed.

Pretty close now. I expect to merge after this round of changes.

**Comment by blackwind** [comment]
One more thing: `ReleaseToGitHub.py` will need to be updated to reflect the new changelog format.

**Comment by topic2k** [comment]
> [line 134] I notice all the other agithub requests contain per_page=100 and page=page. Will NextPage() work without them? If not, fix needed here.

The github api has a default per_page of 30, but i will add per_page=100 to be consistent.

> [line 168] Change to "https://github.com/{0}/{1}/releases/tag/v{2}".format(. Missed the "v".

Should the "v" be added to the link url only, or also to the the link name?
     `# [0.4.5](https://github.com/EventGhost/EventGhost/releases/tag/v0.4.5) (2016-07-12)`
     or
     `# [v0.4.5](https://github.com/topic2k/EventGhost/releases/tag/v0.4.5) (2016-07-12)`

**Comment by blackwind** [comment]
Just the URL.

**Comment by blackwind** [comment]
One last thing: Items enclosed in backticks shouldn't be escaped. #20 comes out as:

> Search for modules in `\[python-install\]\Lib\site-packages` and `%PYTHONPATH%`

Instead of:

> Search for modules in `[python-install]\Lib\site-packages` and `%PYTHONPATH%`

**Comment by blackwind** [comment]
This solution doesn't escape the last portion in a string with multiple backticks, but I've come up with my own solution and will commit after merging.

Do me a small favor and read through [`CONTRIBUTING.md`](https://github.com/EventGhost/EventGhost/blob/master/CONTRIBUTING.md) in its entirety (including the links) before your next PR. There are still a few minor things you're missing. I'm going to hold everyone else who contributes to these standards, so you and I need to lead by example.

Merging now. Great work again!

**Pull request merged**
