### PR TITLE
[System] Add events from #175 to event list.

### PR DESCRIPTION
**Pull request by topic2k**
Add events from #175 to event list. (So they will show up in the add/edit event dialog.)

### CODE REVIEW

**Comment by topic2k** [comment]
If you have it in an branch, just link that here ;)

**Comment by kdschlosser** [comment]
https://github.com/kdschlosser/EventGhost/tree/enhancement-eventspowernotifier

**Comment by topic2k** [comment]
When i look at the [init file](https://github.com/kdschlosser/EventGhost/blob/enhancement-eventspowernotifier/plugins/System/__init__.py) of the System plugin of that branch, it still just has the few events listed:
```python
EVENT_LIST = (
    ("Idle", None),
    ("UnIdle", None),
    ("DriveMounted", None),
    ("DriveRemoved", None),
    ("DeviceAttached", None),
    ("DeviceRemoved", None),
)
```

**Comment by kdschlosser** [comment]
I know...

you have to look at the AddEvent override in the system class. and then look at the powernotifier.py file

**Comment by kdschlosser** [comment]
it's not any voodoo code or anything... it just keeps all the powernotification stuff in one place.. so if any changes need to get made. there is no jumping around that needs to be done.

**Comment by kdschlosser** [comment]
i think the rest of the events aught to be moved to their respective files as well.. it makes it easier when modifying something if everything dealing with whatever it is  your changing is all in one place... instead of being spread out across multiple files..

that is one of the biggest complexities of EG is there are bits here and there and trying to follow it with all the __new__ and @classmethod through a class that subclassed a sunclassed a subclassed class  it's loony tunes to follow. i want to just become harry potter and waive a stick over it... and make it all transform into something that is easy to follow.

**Comment by kdschlosser** [comment]
kind of right up the ally with having the undo handler actually make the different tree items?!?!?! go figure. that is the first place i would go looking for the code that creates the various tree items.. :S

**Comment by topic2k** [comment]
yes, sometimes i think it's best to stop messing around with the current source code and start from scratch using Python 3.  :neckbeard:

**Comment by kdschlosser** [comment]
I am going to have to agree with you on that one... that is one of the reasons why I DO NOT WANT THE JOB OF DEPRECIATING THE XmlIdLink. LOL. My god I tried it once... forget about it...

and I have also tried removing stackless and that proves to be a nightmare only because of how it deals with the dialogs and  tasklets. no matter what i try it always locks up on me. I have also looked into processing to replace it because it functions very much in the same manner for passing data back and forth. But also because all of this hocus pocus if i want to do anything graphically intensive like displaying security cameras (several of them) the whole EG GUI slows to a snails pace. I could hand draw the GUI faster LOL

**Comment by kdschlosser** [comment]
I will tell you this.. If ya want some help. I am for it... BUT there is one condition... 

it has to be multi platform (well screw Mac) so Windows and Linux

**Comment by topic2k** [comment]
And i will tell you this 🤣 : I won't do it. I don't have the time for it (now) and my skills are not good enough for that. Maybe in a year or two.  :joy:

**Comment by topic2k** [comment]
Ok, i reverted my changes and used your's. 😉

**Comment by kdschlosser** [comment]
you didn't have to do all that... it just makes sense to me honestly.. and the fact that the events don't have to be keyed in 2 times. and also i was able to build all of the battery events off the same iterator. I know there are tiny things.. but if you add up all the little tiny things.. they can amount to one big performance hit. and also my first programming experience was on microcontrollers.. that have only 32K storage and 2K ram. LOL so you learned how not to duplicate anything. and how not to set anything into variables if at all possible.. to just pass the bugger right to another function if that is where it was headed.. you will see me do that. I did that in this.

    self.plugin.AddEvents(*CreateEventList(POWER_MESSAGES))

kind of dumb i guess. but when you only have 2K of memory it makes the world of difference and it's hard to break that habit

**Comment by kdschlosser** [comment]
How do you think you get the skills... hell by jumping in feet first... 

and in 2 years from now when you would just be starting.. you could be looking back and laughing at the bumblefuck you made of the code. and you get to go and fix it up...

**Comment by kdschlosser** [comment]
I started coding in python i think about a year and a half ago..  @per1234 knows. he was right there when i started messing with python.. Per was it a year and a half ago? could be 2. don't remember. point in fact.. he is the reason i started messing with python. because of a C++ library he made for a microcontroller.. to communicate with EG I give him all the credit for getting me into this. well.. Him for getting me into it.. and Google for helping me find the answers... OHHHH Google, the hours we have spent together,,,, I should give Google a wedding ring. i spend more time with Her/It then with my own wife...

**Comment by topic2k** [comment]
> you didn't have to do all that... it just makes sense to me honestly.. 

You are right, it fits better in that piece of code. I will merge it if it's ok for you.

**Comment by topic2k** [comment]
> How do you think you get the skills... hell by jumping in feet first...

of course from learning 😉 , but i'm learning sloooowly.  :disappointed:

**Comment by per1234** [comment]
>Per was it a year and a half ago? could be 2.

We met when you opened that issue report regarding the bug you found in my library by throwing huge payloads at it that I had never considered it would need to handle. That was August 2015, so less than 1.5 years. You've come a long way fast, props to Google!

**Comment by kdschlosser** [comment]
fix the \n stuff first... in the descriptions..

and I do not know if you want to also move the events that belong in the other files while you're at it. or if you want to do a separate PR for those

**Comment by kdschlosser** [comment]
@per1234 yeah I know the 400 byte payload. on a device that only has 2048 dynamic available. but usually far less to to libraries it works tho. I managed to get etherevents, Ethernet and the pronto ir blaster onto an uno. it just squeaked by

**Comment by topic2k** [comment]
@kdschlosser: is this PR now ok or would you like to have something changed? If not, maybe approve it? :bowtie:

**Comment by kdschlosser** [comment]
yeah it should be good to go unless you want me to go through the rest of the system plugin and add the missing events and also move them to their respective files? 

I know of one missing event for sure... i do not know what else there may be I would have to  look at the code

but System.ClipboardChanged is not in the list

**Comment by kdschlosser** [comment]
we can always shift things around later...

**Comment by kdschlosser** [comment]
i submitted a PR #182 to change AddEvents so it will now add events to the list instead of overwriting it

**Comment by topic2k** [comment]
Sorry, sometimes i have problems understanding you (be patience with me, i'm German 😀 ). What i think to read: merge this PR +182 and all is well?

**Comment by kdschlosser** [comment]
they are hinged to each other if #182 (or a variation of) is not merged. then the __init__ from the system plugin that i made with these modifications will have to be. because of how it overrides the AddEventList to add to the list instead of replacing it. if ya take a look at my branch on this look at the __init__ and specifically the AddEventList method. I think you will get a better understanding

and maybe we should direct our conversation to that single place.... this jumping around is making me dizzy. the 3 different conversations are really tied together...

I am German as well. don't speak a lick of it.. and I am very patient. so take your time.. I also word things in an odd manner. so if you need to to clarify i will be more then happy to.

**Pull request closed without merging**
